version: "3.9"

services:
  db-master:
    image: postgres:15-alpine
    container_name: postgres_master
    restart: always
    environment:
      POSTGRES_USER: user_master
      POSTGRES_PASSWORD: master_password
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - master_data:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hba_file=/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user_master", "-d", "api_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api-network

  db-replica:
    image: postgres:15-alpine
    container_name: postgres_replica
    restart: always
    depends_on:
      db-master:
        condition: service_healthy
    environment:
      POSTGRES_USER: user_master
      POSTGRES_PASSWORD: master_password
      PGDATA: /var/lib/postgresql/replica_data
    volumes:
      - replica_data:/var/lib/postgresql/replica_data
    entrypoint: >
      bash -c "
      rm -rf /var/lib/postgresql/replica_data &&
      mkdir -p /var/lib/postgresql/replica_data &&
      chown -R postgres:postgres /var/lib/postgresql/replica_data &&
      chmod 700 /var/lib/postgresql/replica_data &&
      su-exec postgres bash -c '
        PGPASSWORD=master_password pg_basebackup -h db-master -D /var/lib/postgresql/replica_data -U user_master -v -P -R -X stream &&
        touch /var/lib/postgresql/replica_data/standby.signal &&
        postgres -D /var/lib/postgresql/replica_data
      '
      "
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user_master", "-d", "api_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_api
    ports:
      - "8080:8080"
    depends_on:
      db-master:
        condition: service_healthy
      db-replica:
        condition: service_healthy
    environment:
      APP_VERSION: v1
      ENVIRONMENT: development
      PG_URL_WRITE: "postgresql://user_master:master_password@db-master:5432/api_db?sslmode=disable"
      PG_URL_READ: "postgresql://user_master:master_password@db-replica:5432/api_db?sslmode=disable"
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  master_data:
  replica_data:
